volumes:
  data:


networks:
  lan_network:
    driver: bridge

services:
  db:
    hostname: postgres
    image: bitnami/postgresql
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - data:/bitnami/postgresql
    ports:
      - 32400:5432
    networks:
      -  lan_network